### ISSUE TITLE
Delete site doesn't automatically update site count

### ISSUE THREAD

**Issue by TrevorLowing** [FlashPanel/flashpanel#31]
I deleted two sites from a host. I navigated back to the servers pags (https://flashpanel.io/servers) and the site count was still 3. I manually refreshed and it went to 1 which was the correct number.

**Comment by nguyentranchung** [comment]
@TrevorLowing 

It seems the page might have disconnected from the WebSocket (real-time update), which is why the site count didn’t update automatically. Refreshing manually resolved it. We’ll look into improving this experience—thank you for letting us know!
